# SQLite version 3.x
#   gem install pg
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  adapter: postgresql
  database: preferences_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: preferences_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: preferences_production
  pool: 5
  timeout: 5000
